server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.ctgdesktop.testeadp.controller
    title: ctg-ctgdesktop-testeadp RESTful APIs
    description: ctg-ctgdesktop-testeadp RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.ctgdesktop.testeadp.controller
        title: actg-ctgdesktop-testeadp Open APIs
        description: ctg-ctgdesktop-testeadp Open API
        version: 1.0.0-SNAPSHOT
